# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'Sponsy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Kingfisher', '3.1'
  # Pods for Sponsy

end
